{
 "title": "Benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Send Transaction count(generator)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transaction-send\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Total TX send(generator)",
   "type": "stat",
   "description": "in each block",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transaction-send\")\n  |> group(columns: [\"_measurement\"])\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tps\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 12h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Round",
   "type": "stat",
   "description": "in each block",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tps\")\n  |> group(columns: [\"_measurement\"])\n  |> count()"
    }
   ]
  },
  { "title": "Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Transaction count(monitor)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"block\")\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Transaction Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"block\")\n  |> aggregateWindow(every: 12h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Total elapsed time(seconds)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expression": "($B - $A) /  1000000000", "type": "math" }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / (($C - $B) /  1000000000)", "type": "math" }
   ]
  },
  {
   "title": "Total Blocks Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"block\")\n  |> count()"
    }
   ]
  },
  {
   "title": "gas used(monitor)",
   "type": "timeseries",
   "description": "in each block",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transaction\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gas\")\n  |> aggregateWindow(every: 5s, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Total Gas Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"transaction\")\n|> filter(fn: (r) => r[\"_field\"] == \"gas\")\n|> aggregateWindow(every: 12h, fn: sum, createEmpty: false)\n|> yield(name: \"sum\")"
    }
   ]
  }
 ]
}